[package]
name = "handsome-voxels"
version = "0.1.0"
authors = ["Duncan <bonsairobo@gmail.com>"]
edition = "2018"

[lib]
name = "handsome_voxels"
path = "src/lib.rs"

[dependencies]
amethyst = "0.15"
bincode = "1.3.1"
derivative = "1.0.4"
failure = "0.1.8"
itertools = "0.9.0"
lazy_static = "1.4.0"
log = "0.4"
ncollide3d = "=0.21.0"
ordered-float = "1.1.0"
rendy = "0.4.1"
serde = "1.0.114"
smallvec = "1.4.1"
structopt = "0.3.15"
thread_profiler = "0.3.0"

ilattice3 = { git = "https://github.com/bonsairobo/ilattice3" }
ilattice3-mesh = { git = "https://github.com/bonsairobo/ilattice3-mesh" }
